-- Consultas de solo lectura para verificar la migracion de evidencia OCR.

SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'tablero_produccion'
  AND COLUMN_NAME IN ('cliente_id', 'pesaje_unico')
ORDER BY COLUMN_NAME;

SELECT TABLE_NAME, ENGINE, TABLE_COLLATION
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'viaje_imagenes';

SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'viaje_imagenes'
ORDER BY ORDINAL_POSITION;

SELECT INDEX_NAME,
       NON_UNIQUE,
       COUNT(*) AS column_count,
       MIN(SEQ_IN_INDEX) AS first_position,
       MAX(SEQ_IN_INDEX) AS last_position,
       GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) AS index_columns
FROM information_schema.STATISTICS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'viaje_imagenes'
GROUP BY INDEX_NAME, NON_UNIQUE
ORDER BY INDEX_NAME;

SELECT CONSTRAINT_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM information_schema.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'viaje_imagenes'
  AND REFERENCED_TABLE_NAME IS NOT NULL;
